defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : floorplan_constrained
    - experiment : floorplan_constrained

hydra:
  job:
    chdir: True
  run:
    dir: ${oc.env:STORAGE_PATH,/mnt/storage}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}
